### ISSUE TITLE
建议用Cabro的那个版本改..

### ISSUE THREAD

**Issue by Qcat0214** [ctank/wow-classic-atlas#1]
之前我修改汉化过他的版本. 那个版本在香草能显示的东西比你现在这个多的多..

链接: https://pan.baidu.com/s/1phRPWe8X0hw3f_MxWLvggQ 提取码: ywsw 

只是个建议...

**Comment by Se7enMuting** [comment]
楼主，台服繁体客户端你这个不能用
这个项目的也不能用...

**Comment by ctank** [comment]
> 之前我修改汉化过他的版本. 那个版本在香草能显示的东西比你现在这个多的多..
> 
> 链接: https://pan.baidu.com/s/1phRPWe8X0hw3f_MxWLvggQ 提取码: ywsw
> 
> 只是个建议...

我这个只是个勉强能用的版本, 平时搬砖bug只能周末看一下, 谢谢各位的提醒了

**Comment by ctank** [comment]
> 楼主，台服繁体客户端你这个不能用
> 这个项目的也不能用...

估
